### ISSUE TITLE
win10 java8 as.bat闪退

### ISSUE THREAD

**Issue by liunewshine** [alibaba/arthas#29] opened 2018-09-15 15:32 UTC
双击后窗口直接消失。。。

**Comment by geekcheng** [comment] 2018-09-17 02:05
C:\Users\jack>E:\arthas-packaging-3.0.0-RC-bin\as.bat
Start arthas failed, exception stack trace:
com.taobao.middleware.cli.InvalidValueException: The value '' is not accepted by 'pid'
        at com.taobao.middleware.cli.impl.DefaultCommandLine.create(DefaultCommandLine.java:342)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.getValue(DefaultCommandLine.java:267)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.getOptionValue(DefaultCommandLine.java:91)
        at com.taobao.arthas.core.Arthas.parse(Arthas.java:40)
        at com.taobao.arthas.core.Arthas.<init>(Arthas.java:23)
        at com.taobao.arthas.core.Arthas.main(Arthas.java:86)
Caused by: java.lang.IllegalArgumentException: java.lang.NumberFormatException: For input string: ""
        at com.taobao.middleware.cli.converters.ConstructorBasedConverter.fromString(ConstructorBasedConverter.java:70)
        at com.taobao.middleware.cli.converters.Converters.create(Converters.java:52)
        at com.taobao.middleware.cli.impl.DefaultCommandLine.create(DefaultCommandLine.java:339)
        ... 5 more
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:592)
        at java.lang.Integer.<init>(Integer.java:867)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.taobao.middleware.cli.converters.ConstructorBasedConverter.fromString(ConstructorBasedConverter.java:67)
        ... 7 more

**Comment by ralf0131** [comment] 2018-09-17 02:26
dup with #21 . I am closing this issue now.

**Closed by ralf0131** 2018-09-17 02:26 UTC

**Comment by hengyunabc** [comment] 2018-09-17 03:31
windows的安装说明已更新： https://alibaba.github.io/arthas/install-detail.html#windows

**Comment by sliver1001** [comment] 2018-10-19 10:11
我在windows下启动时，as.bat pid ，然后依旧报错
![default](https://user-images.githubusercontent.com/41311567/47212323-6ec41980-d3ca-11e8-9905-dd70ff270ec4.png)

**Comment by hengyunabc** [comment] 2018-10-19 12:07
@sliver1001 设置和目标进程一样的 JAVA_HOME ，用同样版本的jdk

**Comment by lailaihaochu** [comment] 2021-04-26 06:30
当启动bat文件时候（环境win10)出现AVA_HOME: D:\Program Files\Java\jdk-11.0.10
telnet port: 3658
http port: 8563
Can not find lib\tools.jar under D:\Program Files\Java\jdk-11.0.10!
If java version <= 1.8, please make sure JAVA_HOME point to a JDK not a JRE.
If java version >= 9, try to run as.bat <pid> --ignore-tools
看着意思是版本不行，那如果使用jdk11就不能使用arthas了么这不对吧！！另外执行./as.sh闪退了
